### ISSUE TITLE
sliders/scrollbars are partially broken due to disabled text selection

### ISSUE THREAD

**Issue by mpgirro** [C453/plex-osx#1]
Though I think the idea to disable text selection/highlighting is good in order to make the application drag-n-droppable, it raises some problems with all the sliders. Basically, they are only clickable now, but sometimes I want to move the scrollbar in a library for quick navigation. Also the sliders for player position and volume are not drag-n-droppable any more.

My advice for a fix/compromise is to only disable text selection for the black navigation bar on the top. This also helps intuitive behaviour (windows in general are moveable on their top bar). Additionally, this restriction could be lifted when a media file is played. In such case text selection could be disable for the whole window (making it drag-n-dropable on the overall video area), with the only exception of the black bar on the bottom where the sliders are located (and this bar fades out after some seconds anyway when you do not move the mouse).

**Comment by C453** [comment]
Fixed in  2ba3fc06cb20b46cd18b01cefef0d09206b7e3d8

Basically didn't allow the window to move if the mouse is over any scroll bar
