### ISSUE TITLE
Update web app to version 0.9.16.4

### ISSUE THREAD

**Issue by mpgirro** [C453/plex-osx#2]
Hi,

I like using this Wrapper of the Plex web app very much. As you may have noticed there was a new release of it today (see [this blog post](https://blog.plex.tv/2016/04/07/seek-plex-shall-find-leveling-web-app/)).

It would be great if you could update this OSX app to it. 

Thanks!

**Comment by C453** [comment]
It should work already, as the app just grabs the webpage

**Comment by mpgirro** [comment]
You're absolutely right, it does. I just did not look at the dashboard, which was the only thing that got polished as it seems.
