### ISSUE TITLE
Remove Plex from name

### ISSUE THREAD

**Issue by lattecowboy** [C453/plex-osx#4]
@C453 Hey there. In the interest of avoiding customer confusion with us at Plex and complying with our trademark policy, please re-name your project by removing the name Plex. Sorry for the hassle!

**Comment by C453** [comment]
ughhhh I have AP Exams to study for ya know 👌👍👍

**Comment by lattecowboy** [comment]
Sorry. Good luck this week and don’t forget to hydrate and sleep! :)
